name: Paper Validator CI
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Code Style Check
        run: flake8 src tests --max-line-length=120
      - name: Run Tests with Coverage
        run: |
          python -m pytest tests/ --cov=src --cov-report=xml
          if (-not (Test-Path coverage.xml)) { Exit 1 }

      # 修正缩进并重新启用上传步骤
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        if: success()  # 仅在测试成功时上传
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          verbose: true
          flags: windows,python
          slug: xaqing/paper

      - name: Network Diagnostics
        run: |
          curl -v https://codecov.io/health
          ping codecov.io -n 3