name: Paper Validator CI
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Code Style Check
        run: flake8 src tests --max-line-length=120
      - name: Run Tests with Coverage
        run: |
          python -m pytest tests/ --cov=src --cov-report=xml
          # 增强路径验证
          Write-Output "当前工作目录：$(Get-Location)"
          Get-ChildItem coverage.xml | % { 
              Write-Output "文件路径：$($_.FullName)"
              Write-Output "文件大小：$($_.Length) bytes" 
          }

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          verbose: true
          working-directory: ${{ github.workspace }}
          fail_ci_if_error: true

      - name: Network Diagnostics
        run: |
          # 增强路径验证
          Write-Output "工作目录绝对路径: ${{ github.workspace }}"
          Get-ChildItem ${{ github.workspace }} -Recurse -Filter coverage.xml
          
          # 使用原生PowerShell命令上传测试
          try {
              $response = Invoke-RestMethod -Uri "https://codecov.io/upload/v2" `
                  -Method Post `
                  -InFile coverage.xml `
                  -Headers @{ "Authorization" = "Bearer $Env:CODECOV_TOKEN" }
              Write-Output "上传响应: $($response | ConvertTo-Json)"
          } catch {
              Write-Output "::error::手动上传失败: $($_.Exception.Message)"
          }